// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz70sZdCyp54vYAd4sbqoeIk2bVArwXy0',
    appId: '1:458222128674:web:b060834dbc6ae6a5d7447b',
    messagingSenderId: '458222128674',
    projectId: 'login-assignment-401c6',
    authDomain: 'login-assignment-401c6.firebaseapp.com',
    storageBucket: 'login-assignment-401c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDamqz6xOIe-64iP4LjfspuYYDDjOuBCS4',
    appId: '1:458222128674:android:7af799b09d5c1b1fd7447b',
    messagingSenderId: '458222128674',
    projectId: 'login-assignment-401c6',
    storageBucket: 'login-assignment-401c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOiB24uxqnNRHgwGl7Ls9O06cUw0VXRus',
    appId: '1:458222128674:ios:1dcb68431977ccdbd7447b',
    messagingSenderId: '458222128674',
    projectId: 'login-assignment-401c6',
    storageBucket: 'login-assignment-401c6.appspot.com',
    iosClientId: '458222128674-6u5m09kjcdabh0qqo8g18kgd5j97n044.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOiB24uxqnNRHgwGl7Ls9O06cUw0VXRus',
    appId: '1:458222128674:ios:1dcb68431977ccdbd7447b',
    messagingSenderId: '458222128674',
    projectId: 'login-assignment-401c6',
    storageBucket: 'login-assignment-401c6.appspot.com',
    iosClientId: '458222128674-6u5m09kjcdabh0qqo8g18kgd5j97n044.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAssignment',
  );
}
